require: rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - bin/bundle
    - 'bin/**'
    - 'docs/**'
    - 'vendor/**'
    - 'tmp/**'
    - 'lib/**'
    - 'public/**'
    - 'storage/**'